export interface TermsSection {
  title: string;
  paragraphs: string[];
  listItems?: string[];
  paragraphsAfterList?: string[];
}

export interface TermsOfServiceConfig {
  lastUpdated: string;
  title: string;
  intro?: string;
  sections: TermsSection[];
  contactEmail: string;
}

const contactEmail = 'hello@affsquad.com';

export const termsOfServiceConfig: TermsOfServiceConfig = {
  lastUpdated: '01/01/2026',
  title: 'Terms of Service',
  contactEmail,
  intro: 'These Terms of Service govern your access to and use of Projekto. By using the website, you agree to these Terms. If you do not agree, please discontinue use of the service.',
  sections: [
    {
      title: '1. Service Overview',
      paragraphs: [
        'Projekto is an online tool designed to provide high-level estimates of development time and budget for web and mobile application projects.',
      ],
      paragraphsAfterList: [
        'All outputs are indicative estimates and are provided for informational purposes only.',
      ],
    },
    {
      title: '2. No Professional Advice or Guarantees',
      paragraphs: [
        'Projekto does not provide legal, financial, or professional consulting services.',
        'Estimates generated by the platform:',
      ],
      listItems: [
        'Are not binding quotes',
        'Do not constitute contractual offers',
        'May differ from real-world project costs and timelines',
      ],
      paragraphsAfterList: [
        'Actual outcomes depend on numerous variables, including scope, requirements, technology choices, and execution.',
      ],
    },
    {
      title: '3. Acceptable Use',
      paragraphs: [
        'By using Projekto, you agree to:',
      ],
      listItems: [
        'Use the service only for lawful purposes',
        'Refrain from attempting to disrupt, reverse-engineer, or abuse the platform',
        'Not misuse or copy the calculator logic, content, or design without authorization',
      ],
    },
    {
      title: '4. Intellectual Property',
      paragraphs: [
        'All intellectual property associated with Projekto — including software logic, content, design elements, and branding — remains the exclusive property of Projekto unless otherwise stated.',
      ],
      paragraphsAfterList: [
        'Unauthorized reproduction or redistribution is prohibited.',
      ],
    },
    {
      title: '5. Limitation of Liability',
      paragraphs: [
        'To the fullest extent permitted by law:',
      ],
      listItems: [
        'Projekto shall not be liable for any direct, indirect, incidental, or consequential damages',
        'We are not responsible for decisions, losses, or outcomes resulting from reliance on calculator estimates',
        'Use of the service is at your own discretion and risk',
      ],
    },
    {
      title: '6. Service Availability',
      paragraphs: [
        'We aim to ensure reliable availability but do not guarantee uninterrupted or error-free access. We reserve the right to modify, suspend, or discontinue any part of the service at any time.',
      ],
    },
    {
      title: '7. External Links',
      paragraphs: [
        'Projekto may include links to third-party websites. We are not responsible for the content, policies, or practices of such external sites.',
      ],
    },
    {
      title: '8. Governing Law',
      paragraphs: [
        'These Terms shall be governed by and interpreted in accordance with the laws of the Republic of Poland and applicable European Union regulations.',
      ],
    },
    {
      title: '9. Changes to These Terms',
      paragraphs: [
        'We may revise these Terms periodically. Continued use of Projekto following any updates constitutes acceptance of the revised Terms.',
      ],
    },
    {
      title: '10. Contact Information',
      paragraphs: [
        'For questions regarding these Terms, please contact:',
        `Email: ${contactEmail}`,
      ],
    },
  ],
};

